---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.1-bullseye

inputs:
  - name: log.go
    path: log.go

run:
  path: log.go/ci/scripts/build.sh
